# Generated by Django 5.2.8 on 2026-04-06 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='district',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Aadhar Number'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='interested_in_entrance_coaching',
            field=models.BooleanField(default=False, verbose_name='Interested in Entrance Coaching?'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_whatsapp_number',
            field=models.BooleanField(default=False, verbose_name='Is this number using WhatsApp?'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_stream',
            field=models.CharField(blank=True, max_length=100, verbose_name='If Others, specify'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='preferred_stream',
            field=models.CharField(blank=True, choices=[('NEET', 'NEET'), ('KEAM', 'KEAM'), ('JEE', 'JEE'), ('CUET', 'CUET'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.course', verbose_name='Interested Course'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's/Guardian's Name"),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.section', verbose_name='Section/Department'),
        ),
    ]
