# Generated by Django 5.2.8 on 2026-04-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_template', models.TextField(default='Hi {name}, your application for {course} has been received. Your application number is {app_no}.', help_text='Use {name}, {course}, and {app_no} as placeholders.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
